### ISSUE TITLE
BUG: getting error when typing and running  node nodeServer.js

### ISSUE THREAD

**Issue by Glaferg** [amandaghassaei/ScratchSerialExtension#3]
i type this in after running and installing everything and this happens:

Marks-MacBook-Pro:~ gabriel$ node nodeServer.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/gabriel/nodeServer.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Marks-MacBook-Pro:~ gabriel$ 

please help

**Comment by BlaT2512** [comment]
Make sure you are in the directory of the file nodeServer.js (use cd to set the directory of the folder containing nodeServer.js)
